\documentclass[12pt,a4paper]{article}
    \setlength\parindent{0pt}
    \usepackage{geometry}
    \usepackage{graphicx}
    \usepackage{grffile}
    \geometry{margin=0.5in}
    \begin{document}

    \section*{Hogfish}


    Species: \emph{Lachnolaimus maximus}, Stock code: Hogfish - Florida Keys - East Florida

Region: Southeast Shelf

Marine Ecoregion: Florida Keys - East Florida

Reconstructed catch data used from years 1986 - 2012 

 For figure captions and method see http://www.seaaroundus.org/cmsy-method

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_MAN.jpg}
    \end{figure}

    \textbf{Results for management (based on BSM analysis)}\\

Fmsy = 0.0927, 95\% CL = 0.0522 - 0.139 (if B $>$ 1/2 Bmsy then Fmsy = 0.5 r)

Fmsy = 0.0739, 95\% CL = 0.0416 - 0.111 (r and Fmsy are linearly reduced if B $<$ 1/2 Bmsy)

MSY = 26.1,  95\% CL = 19.3 - 36.2; Bmsy = 284,  95\% CL = 180 - 498 (1000 tonnes)

Biomass in last year = 114, 95\% CL = 71.4 - 194 (1000 tonnes)

B/Bmsy in last year = 0.398, 95\% CL = 0.279 - 0.571

Fishing mortality in last year = 0.0291, 95\% CL =0.0157 - 0.051

F/Fmsy  = 0.4, 95\% CL = 0.208 - 0.828 

 Comment: NOAA Assessment model SS3. RF OK 

    \pagebreak

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_AN.jpg}
    \end{figure}

    \textbf{Results of CMSY analysis conducted in JAGS}\\

r = 0.322, 95\% CL = 0.206 - 0.429; k = 315, 95\% CL = 241 - 496 (1000 tonnes)

MSY = 25.4, 95\% CL = 19.7 - 33.4 (1000 tonnes/year)

Relative biomass last year = 0.129 k, 95\% CL = 0.0443 - 0.271

Exploitation F/(r/2) in last year = 1.11 \\

\textbf{Results from Bayesian Schaefer model using catch and CPUE}\\

r = 0.185, 95\% CL = 0.104 - 0.279; k = 569, 95\% CL = 359 - 996

r-k log correlation = -0.813

MSY = 26.1, 95\% CL = 19.3 - 36.2 (1000 tonnes/year)

Relative biomass in last year = 0.129 k, 95\% CL = 0.0443 - 0.271

Exploitation F/(r/2) in last year = 0.582

q = 3.53, 95\% CL = 2.07 - 5.27

Prior range of q = 1.16 - 28.4

Relative abundance data type = CPUE

Prior initial relative biomass = 0.15 - 0.3 expert

Prior intermediate relative biomass = 0.0678 - 0.323 in year 2005 default

Prior final relative biomass = 0.02 - 0.25 expert

Prior range for r = 0.2 - 0.8 default, prior range for k = 69.7 - 427 (1000 tonnes) default

Source for relative biomass: 

NOAA Fisheries. (2020). Assessment Summary Data. Retrieved from www.st.nmfs.noaa.gov/stocksmart. 12/13/2020

    \end{document}