\documentclass[12pt,a4paper]{article}
    \setlength\parindent{0pt}
    \usepackage{geometry}
    \usepackage{graphicx}
    \usepackage{grffile}
    \geometry{margin=0.5in}
    \begin{document}

    \section*{Hogfish}


    Species: \emph{Lachnolaimus maximus}, Stock code: Hogfish - Florida Keys - East Florida

Region: Southeast Shelf

Marine Ecoregion: Florida Keys - East Florida

Reconstructed catch data used from years 1986 - 2012 

 For figure captions and method see http://www.seaaroundus.org/cmsy-method

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_MAN.jpg}
    \end{figure}

    \textbf{Results for management (based on BSM analysis)}\\

Fmsy = 0.0896, 95\% CL = 0.0547 - 0.147 (if B $>$ 1/2 Bmsy then Fmsy = 0.5 r)

Fmsy = 0.0708, 95\% CL = 0.0432 - 0.116 (r and Fmsy are linearly reduced if B $<$ 1/2 Bmsy)

MSY = 26.6,  95\% CL = 19.3 - 37; Bmsy = 296,  95\% CL = 174 - 495 (1000 tonnes)

Biomass in last year = 118, 95\% CL = 70.9 - 197 (1000 tonnes)

B/Bmsy in last year = 0.395, 95\% CL = 0.276 - 0.566

Fishing mortality in last year = 0.0285, 95\% CL =0.0159 - 0.0507

F/Fmsy  = 0.401, 95\% CL = 0.209 - 0.845 

 Comment: NOAA Assessment model SS3. RF OK 

    \pagebreak

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_AN.jpg}
    \end{figure}

    \textbf{Results of CMSY analysis conducted in JAGS}\\

r = 0.326, 95\% CL = 0.21 - 0.434; k = 313, 95\% CL = 237 - 489 (1000 tonnes)

MSY = 25.5, 95\% CL = 19.7 - 33 (1000 tonnes/year)

Relative biomass last year = 0.128 k, 95\% CL = 0.0402 - 0.266

Exploitation F/(r/2) in last year = 1.1 \\

\textbf{Results from Bayesian Schaefer model using catch and CPUE}\\

r = 0.179, 95\% CL = 0.109 - 0.294; k = 593, 95\% CL = 347 - 990

r-k log correlation = -0.797

MSY = 26.6, 95\% CL = 19.3 - 37 (1000 tonnes/year)

Relative biomass in last year = 0.128 k, 95\% CL = 0.0402 - 0.266

Exploitation F/(r/2) in last year = 0.58

q = 3.41, 95\% CL = 2.12 - 5.55

Prior range of q = 1.14 - 28

Relative abundance data type = CPUE

Prior initial relative biomass = 0.15 - 0.3 expert

Prior intermediate relative biomass = 0.0678 - 0.323 in year 2005 default

Prior final relative biomass = 0.02 - 0.25 expert

Prior range for r = 0.2 - 0.8 default, prior range for k = 70.8 - 435 (1000 tonnes) default

Source for relative biomass: 

NOAA Fisheries. (2020). Assessment Summary Data. Retrieved from www.st.nmfs.noaa.gov/stocksmart. 12/13/2020

    \end{document}