\documentclass[12pt,a4paper]{article}
    \setlength\parindent{0pt}
    \usepackage{geometry}
    \usepackage{graphicx}
    \usepackage{grffile}
    \geometry{margin=0.5in}
    \begin{document}

    \section*{Hogfish}


    Species: \emph{Lachnolaimus maximus}, Stock code: Hogfish - Florida Keys - East Florida

Region: Southeast Shelf

Marine Ecoregion: Florida Keys - East Florida

Reconstructed catch data used from years 1986 - 2012 

 For figure captions and method see http://www.seaaroundus.org/cmsy-method

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_MAN.jpg}
    \end{figure}

    \textbf{Results for management (based on BSM analysis)}\\

Fmsy = 0.0873, 95\% CL = 0.0536 - 0.13 (if B $>$ 1/2 Bmsy then Fmsy = 0.5 r)

Fmsy = 0.0692, 95\% CL = 0.0425 - 0.103 (r and Fmsy are linearly reduced if B $<$ 1/2 Bmsy)

MSY = 26.6,  95\% CL = 19.7 - 37.1; Bmsy = 302,  95\% CL = 207 - 518 (1000 tonnes)

Biomass in last year = 123, 95\% CL = 76.8 - 202 (1000 tonnes)

B/Bmsy in last year = 0.397, 95\% CL = 0.283 - 0.575

Fishing mortality in last year = 0.0269, 95\% CL =0.0154 - 0.0478

F/Fmsy  = 0.392, 95\% CL = 0.202 - 0.821 

 Comment: NOAA Assessment model SS3. RF OK 

    \pagebreak

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_AN.jpg}
    \end{figure}

    \textbf{Results of CMSY analysis conducted in JAGS}\\

r = 0.322, 95\% CL = 0.201 - 0.434; k = 325, 95\% CL = 246 - 525 (1000 tonnes)

MSY = 26.2, 95\% CL = 20.2 - 33.9 (1000 tonnes/year)

Relative biomass last year = 0.125 k, 95\% CL = 0.0501 - 0.271

Exploitation F/(r/2) in last year = 1.16 \\

\textbf{Results from Bayesian Schaefer model using catch and CPUE}\\

r = 0.175, 95\% CL = 0.107 - 0.261; k = 604, 95\% CL = 415 - 1035

r-k log correlation = -0.772

MSY = 26.6, 95\% CL = 19.7 - 37.1 (1000 tonnes/year)

Relative biomass in last year = 0.125 k, 95\% CL = 0.0501 - 0.271

Exploitation F/(r/2) in last year = 0.6

q = 3.27, 95\% CL = 2.06 - 4.81

Prior range of q = 1.12 - 28.2

Relative abundance data type = CPUE

Prior initial relative biomass = 0.15 - 0.3 expert

Prior intermediate relative biomass = 0.0678 - 0.323 in year 2005 default

Prior final relative biomass = 0.02 - 0.25 expert

Prior range for r = 0.2 - 0.8 default, prior range for k = 70.2 - 443 (1000 tonnes) default

Source for relative biomass: 

NOAA Fisheries. (2020). Assessment Summary Data. Retrieved from www.st.nmfs.noaa.gov/stocksmart. 12/13/2020

    \end{document}