\documentclass[12pt,a4paper]{article}
    \setlength\parindent{0pt}
    \usepackage{geometry}
    \usepackage{graphicx}
    \usepackage{grffile}
    \geometry{margin=0.5in}
    \begin{document}

    \section*{Hogfish}


    Species: \emph{Lachnolaimus maximus}, Stock code: Hogfish - Florida Keys - East Florida

Region: Southeast Shelf

Marine Ecoregion: Florida Keys - East Florida

Reconstructed catch data used from years 1986 - 2012 

 For figure captions and method see http://www.seaaroundus.org/cmsy-method

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_MAN.jpg}
    \end{figure}

    \textbf{Results for management (based on BSM analysis)}\\

Fmsy = 0.0862, 95\% CL = 0.0535 - 0.134 (if B $>$ 1/2 Bmsy then Fmsy = 0.5 r)

Fmsy = 0.0697, 95\% CL = 0.0432 - 0.108 (r and Fmsy are linearly reduced if B $<$ 1/2 Bmsy)

MSY = 26,  95\% CL = 19.1 - 35.4; Bmsy = 304,  95\% CL = 190 - 525 (1000 tonnes)

Biomass in last year = 123, 95\% CL = 72.9 - 206 (1000 tonnes)

B/Bmsy in last year = 0.404, 95\% CL = 0.288 - 0.562

Fishing mortality in last year = 0.0274, 95\% CL =0.0153 - 0.0501

F/Fmsy  = 0.392, 95\% CL = 0.207 - 0.835 

 Comment: NOAA Assessment model SS3. RF OK 

    \pagebreak

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_AN.jpg}
    \end{figure}

    \textbf{Results of CMSY analysis conducted in JAGS}\\

r = 0.323, 95\% CL = 0.206 - 0.424; k = 319, 95\% CL = 237 - 507 (1000 tonnes)

MSY = 25.7, 95\% CL = 20.1 - 33.8 (1000 tonnes/year)

Relative biomass last year = 0.119 k, 95\% CL = 0.0456 - 0.259

Exploitation F/(r/2) in last year = 1.26 \\

\textbf{Results from Bayesian Schaefer model using catch and CPUE}\\

r = 0.172, 95\% CL = 0.107 - 0.267; k = 608, 95\% CL = 381 - 1050

r-k log correlation = -0.795

MSY = 26, 95\% CL = 19.1 - 35.4 (1000 tonnes/year)

Relative biomass in last year = 0.119 k, 95\% CL = 0.0456 - 0.259

Exploitation F/(r/2) in last year = 0.637

q = 3.28, 95\% CL = 1.98 - 5.19

Prior range of q = 1.16 - 28.6

Relative abundance data type = CPUE

Prior initial relative biomass = 0.15 - 0.3 expert

Prior intermediate relative biomass = 0.0678 - 0.323 in year 2005 default

Prior final relative biomass = 0.02 - 0.25 expert

Prior range for r = 0.2 - 0.8 default, prior range for k = 69.1 - 428 (1000 tonnes) default

Source for relative biomass: 

NOAA Fisheries. (2020). Assessment Summary Data. Retrieved from www.st.nmfs.noaa.gov/stocksmart. 12/13/2020

    \end{document}