\documentclass[12pt,a4paper]{article}
    \setlength\parindent{0pt}
    \usepackage{geometry}
    \usepackage{graphicx}
    \usepackage{grffile}
    \geometry{margin=0.5in}
    \begin{document}

    \section*{Hogfish}


    Species: \emph{Lachnolaimus maximus}, Stock code: Hogfish - Florida Keys - East Florida

Region: Southeast Shelf

Marine Ecoregion: Florida Keys - East Florida

Reconstructed catch data used from years 1986 - 2012 

 For figure captions and method see http://www.seaaroundus.org/cmsy-method

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_MAN.jpg}
    \end{figure}

    \textbf{Results for management (based on BSM analysis)}\\

Fmsy = 0.0858, 95\% CL = 0.0531 - 0.141 (if B $>$ 1/2 Bmsy then Fmsy = 0.5 r)

Fmsy = 0.0681, 95\% CL = 0.0421 - 0.112 (r and Fmsy are linearly reduced if B $<$ 1/2 Bmsy)

MSY = 26.4,  95\% CL = 19.9 - 36.5; Bmsy = 308,  95\% CL = 187 - 498 (1000 tonnes)

Biomass in last year = 122, 95\% CL = 72.8 - 202 (1000 tonnes)

B/Bmsy in last year = 0.397, 95\% CL = 0.278 - 0.558

Fishing mortality in last year = 0.0274, 95\% CL =0.0154 - 0.0492

F/Fmsy  = 0.401, 95\% CL = 0.212 - 0.825 

 Comment: NOAA Assessment model SS3. RF OK 

    \pagebreak

    \begin{figure}[ht]
    \centering
    \includegraphics[width=1.00\textwidth ext=.jpg type=jpg]{Hogfish - Florida Keys - East Florida_AN.jpg}
    \end{figure}

    \textbf{Results of CMSY analysis conducted in JAGS}\\

r = 0.317, 95\% CL = 0.2 - 0.422; k = 323, 95\% CL = 239 - 514 (1000 tonnes)

MSY = 25.6, 95\% CL = 20 - 33.5 (1000 tonnes/year)

Relative biomass last year = 0.125 k, 95\% CL = 0.0455 - 0.252

Exploitation F/(r/2) in last year = 1.13 \\

\textbf{Results from Bayesian Schaefer model using catch and CPUE}\\

r = 0.172, 95\% CL = 0.106 - 0.283; k = 616, 95\% CL = 373 - 995

r-k log correlation = -0.81

MSY = 26.4, 95\% CL = 19.9 - 36.5 (1000 tonnes/year)

Relative biomass in last year = 0.125 k, 95\% CL = 0.0455 - 0.252

Exploitation F/(r/2) in last year = 0.598

q = 3.27, 95\% CL = 2.06 - 5.23

Prior range of q = 1.13 - 28.9

Relative abundance data type = CPUE

Prior initial relative biomass = 0.15 - 0.3 expert

Prior intermediate relative biomass = 0.0678 - 0.323 in year 2005 default

Prior final relative biomass = 0.02 - 0.25 expert

Prior range for r = 0.2 - 0.8 default, prior range for k = 68.5 - 439 (1000 tonnes) default

Source for relative biomass: 

NOAA Fisheries. (2020). Assessment Summary Data. Retrieved from www.st.nmfs.noaa.gov/stocksmart. 12/13/2020

    \end{document}