# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/biomass.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/biomass.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17surimi/v1/biomass.proto\x12\tsurimi.v1\"R\n\x0b\x42iomassGrid\x12\x14\n\x0cspecies_code\x18\x01 \x01(\t\x12-\n\rbiomass_cells\x18\x02 \x03(\x0b\x32\x16.surimi.v1.BiomassCell\"C\n\x0b\x42iomassCell\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x0f\n\x07\x62iomass\x18\x03 \x01(\x01\"Y\n\x0e\x42iomassSummary\x12\x18\n\x10measurement_unit\x18\x01 \x01(\t\x12-\n\rbiomass_grids\x18\x02 \x03(\x0b\x32\x16.surimi.v1.BiomassGridB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.biomass_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_BIOMASSGRID']._serialized_start=38
  _globals['_BIOMASSGRID']._serialized_end=120
  _globals['_BIOMASSCELL']._serialized_start=122
  _globals['_BIOMASSCELL']._serialized_end=189
  _globals['_BIOMASSSUMMARY']._serialized_start=191
  _globals['_BIOMASSSUMMARY']._serialized_end=280
# @@protoc_insertion_point(module_scope)
