# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from surimi.v1 import controller_pb2 as surimi_dot_v1_dot_controller__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in surimi/v1/controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitSimulation = channel.unary_unary(
                '/surimi.v1.ControllerService/InitSimulation',
                request_serializer=surimi_dot_v1_dot_controller__pb2.InitSimulationRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_controller__pb2.InitSimulationResponse.FromString,
                _registered_method=True)
        self.RunSimulation = channel.unary_unary(
                '/surimi.v1.ControllerService/RunSimulation',
                request_serializer=surimi_dot_v1_dot_controller__pb2.RunSimulationRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_controller__pb2.RunSimulationResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.InitSimulation,
                    request_deserializer=surimi_dot_v1_dot_controller__pb2.InitSimulationRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_controller__pb2.InitSimulationResponse.SerializeToString,
            ),
            'RunSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=surimi_dot_v1_dot_controller__pb2.RunSimulationRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_controller__pb2.RunSimulationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surimi.v1.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surimi.v1.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.ControllerService/InitSimulation',
            surimi_dot_v1_dot_controller__pb2.InitSimulationRequest.SerializeToString,
            surimi_dot_v1_dot_controller__pb2.InitSimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.ControllerService/RunSimulation',
            surimi_dot_v1_dot_controller__pb2.RunSimulationRequest.SerializeToString,
            surimi_dot_v1_dot_controller__pb2.RunSimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
