# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/disposition.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/disposition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsurimi/v1/disposition.proto\x12\tsurimi.v1\"q\n\x0f\x44ispositionGrid\x12\x11\n\tgear_code\x18\x01 \x01(\t\x12\x14\n\x0cspecies_code\x18\x02 \x01(\t\x12\x35\n\x11\x64isposition_cells\x18\x03 \x03(\x0b\x32\x1a.surimi.v1.DispositionCell\"y\n\x0f\x44ispositionCell\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x13\n\x0bgross_catch\x18\x03 \x01(\x01\x12\x15\n\rlive_discards\x18\x04 \x01(\x01\x12\x15\n\rdead_discards\x18\x05 \x01(\x01\x42!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.disposition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_DISPOSITIONGRID']._serialized_start=42
  _globals['_DISPOSITIONGRID']._serialized_end=155
  _globals['_DISPOSITIONCELL']._serialized_start=157
  _globals['_DISPOSITIONCELL']._serialized_end=278
# @@protoc_insertion_point(module_scope)
