# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/ecology.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/ecology.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from surimi.v1 import biomass_pb2 as surimi_dot_v1_dot_biomass__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17surimi/v1/ecology.proto\x12\tsurimi.v1\x1a\x17surimi/v1/biomass.proto\"*\n\x11GetBiomassRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"]\n\x12GetBiomassResponse\x12\x18\n\x10measurement_unit\x18\x01 \x01(\t\x12-\n\rbiomass_grids\x18\x02 \x03(\x0b\x32\x16.surimi.v1.BiomassGrid2[\n\x0e\x45\x63ologyService\x12I\n\nGetBiomass\x12\x1c.surimi.v1.GetBiomassRequest\x1a\x1d.surimi.v1.GetBiomassResponseB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.ecology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_GETBIOMASSREQUEST']._serialized_start=63
  _globals['_GETBIOMASSREQUEST']._serialized_end=105
  _globals['_GETBIOMASSRESPONSE']._serialized_start=107
  _globals['_GETBIOMASSRESPONSE']._serialized_end=200
  _globals['_ECOLOGYSERVICE']._serialized_start=202
  _globals['_ECOLOGYSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
