# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from surimi.v1 import fishery_pb2 as surimi_dot_v1_dot_fishery__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in surimi/v1/fishery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FisheryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCatchDisposition = channel.unary_unary(
                '/surimi.v1.FisheryService/GetCatchDisposition',
                request_serializer=surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionResponse.FromString,
                _registered_method=True)
        self.UpdateCatchDisposition = channel.unary_unary(
                '/surimi.v1.FisheryService/UpdateCatchDisposition',
                request_serializer=surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionResponse.FromString,
                _registered_method=True)


class FisheryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCatchDisposition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCatchDisposition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FisheryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCatchDisposition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatchDisposition,
                    request_deserializer=surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionResponse.SerializeToString,
            ),
            'UpdateCatchDisposition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCatchDisposition,
                    request_deserializer=surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surimi.v1.FisheryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surimi.v1.FisheryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FisheryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCatchDisposition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.FisheryService/GetCatchDisposition',
            surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionRequest.SerializeToString,
            surimi_dot_v1_dot_fishery__pb2.GetCatchDispositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCatchDisposition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.FisheryService/UpdateCatchDisposition',
            surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionRequest.SerializeToString,
            surimi_dot_v1_dot_fishery__pb2.UpdateCatchDispositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
