# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/market.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from surimi.v1 import sales_pb2 as surimi_dot_v1_dot_sales__pb2
from surimi.v1 import species_price_pb2 as surimi_dot_v1_dot_species__price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16surimi/v1/market.proto\x12\tsurimi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15surimi/v1/sales.proto\x1a\x1dsurimi/v1/species_price.proto\"0\n\x17GetSpeciesPricesRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"Z\n\x18GetSpeciesPricesResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\'\n\x06prices\x18\x02 \x03(\x0b\x32\x17.surimi.v1.SpeciesPrice\"\\\n\x1aUpdateSpeciesPricesRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\'\n\x06prices\x18\x02 \x03(\x0b\x32\x17.surimi.v1.SpeciesPrice\"4\n\x1bUpdateSpeciesPricesResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"\x90\x01\n\x0fGetSalesRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x33\n\x0fstart_date_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_date_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\x10GetSalesResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x30\n\x0fsales_summaries\x18\x02 \x03(\x0b\x32\x17.surimi.v1.SalesSummary\"\xc5\x01\n\x12UpdateSalesRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x33\n\x0fstart_date_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_date_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0fsales_summaries\x18\x04 \x03(\x0b\x32\x17.surimi.v1.SalesSummary\",\n\x13UpdateSalesResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t2\xe5\x02\n\rMarketService\x12[\n\x10GetSpeciesPrices\x12\".surimi.v1.GetSpeciesPricesRequest\x1a#.surimi.v1.GetSpeciesPricesResponse\x12\x64\n\x13UpdateSpeciesPrices\x12%.surimi.v1.UpdateSpeciesPricesRequest\x1a&.surimi.v1.UpdateSpeciesPricesResponse\x12\x43\n\x08GetSales\x12\x1a.surimi.v1.GetSalesRequest\x1a\x1b.surimi.v1.GetSalesResponse\x12L\n\x0bUpdateSales\x12\x1d.surimi.v1.UpdateSalesRequest\x1a\x1e.surimi.v1.UpdateSalesResponseB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_GETSPECIESPRICESREQUEST']._serialized_start=124
  _globals['_GETSPECIESPRICESREQUEST']._serialized_end=172
  _globals['_GETSPECIESPRICESRESPONSE']._serialized_start=174
  _globals['_GETSPECIESPRICESRESPONSE']._serialized_end=264
  _globals['_UPDATESPECIESPRICESREQUEST']._serialized_start=266
  _globals['_UPDATESPECIESPRICESREQUEST']._serialized_end=358
  _globals['_UPDATESPECIESPRICESRESPONSE']._serialized_start=360
  _globals['_UPDATESPECIESPRICESRESPONSE']._serialized_end=412
  _globals['_GETSALESREQUEST']._serialized_start=415
  _globals['_GETSALESREQUEST']._serialized_end=559
  _globals['_GETSALESRESPONSE']._serialized_start=561
  _globals['_GETSALESRESPONSE']._serialized_end=652
  _globals['_UPDATESALESREQUEST']._serialized_start=655
  _globals['_UPDATESALESREQUEST']._serialized_end=852
  _globals['_UPDATESALESRESPONSE']._serialized_start=854
  _globals['_UPDATESALESRESPONSE']._serialized_end=898
  _globals['_MARKETSERVICE']._serialized_start=901
  _globals['_MARKETSERVICE']._serialized_end=1258
# @@protoc_insertion_point(module_scope)
