# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/stock_assessment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/stock_assessment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n surimi/v1/stock_assessment.proto\x12\tsurimi.v1\"5\n\x1c\x43reateStockAssessmentRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"6\n\x1d\x43reateStockAssessmentResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t2\x84\x01\n\x16StockAssessmentService\x12j\n\x15\x43reateStockAssessment\x12\'.surimi.v1.CreateStockAssessmentRequest\x1a(.surimi.v1.CreateStockAssessmentResponseB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.stock_assessment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_CREATESTOCKASSESSMENTREQUEST']._serialized_start=47
  _globals['_CREATESTOCKASSESSMENTREQUEST']._serialized_end=100
  _globals['_CREATESTOCKASSESSMENTRESPONSE']._serialized_start=102
  _globals['_CREATESTOCKASSESSMENTRESPONSE']._serialized_end=156
  _globals['_STOCKASSESSMENTSERVICE']._serialized_start=159
  _globals['_STOCKASSESSMENTSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
