# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/workflow.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18surimi/v1/workflow.proto\x12\tsurimi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n\x11InitialiseRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x13\n\x0bscenario_id\x18\x02 \x01(\t\x12\x33\n\x0fstart_date_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tstep_size\x18\x04 \x01(\t\"+\n\x12InitialiseResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"(\n\x0f\x46inaliseRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\")\n\x10\x46inaliseResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"&\n\rCancelRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"\'\n\x0e\x43\x61ncelResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\",\n\x13SimulateStepRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"-\n\x14SimulateStepResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t2\xb1\x02\n\x0fWorkflowService\x12I\n\nInitialise\x12\x1c.surimi.v1.InitialiseRequest\x1a\x1d.surimi.v1.InitialiseResponse\x12O\n\x0cSimulateStep\x12\x1e.surimi.v1.SimulateStepRequest\x1a\x1f.surimi.v1.SimulateStepResponse\x12\x43\n\x08\x46inalise\x12\x1a.surimi.v1.FinaliseRequest\x1a\x1b.surimi.v1.FinaliseResponse\x12=\n\x06\x43\x61ncel\x12\x18.surimi.v1.CancelRequest\x1a\x19.surimi.v1.CancelResponseB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_INITIALISEREQUEST']._serialized_start=73
  _globals['_INITIALISEREQUEST']._serialized_end=208
  _globals['_INITIALISERESPONSE']._serialized_start=210
  _globals['_INITIALISERESPONSE']._serialized_end=253
  _globals['_FINALISEREQUEST']._serialized_start=255
  _globals['_FINALISEREQUEST']._serialized_end=295
  _globals['_FINALISERESPONSE']._serialized_start=297
  _globals['_FINALISERESPONSE']._serialized_end=338
  _globals['_CANCELREQUEST']._serialized_start=340
  _globals['_CANCELREQUEST']._serialized_end=378
  _globals['_CANCELRESPONSE']._serialized_start=380
  _globals['_CANCELRESPONSE']._serialized_end=419
  _globals['_SIMULATESTEPREQUEST']._serialized_start=421
  _globals['_SIMULATESTEPREQUEST']._serialized_end=465
  _globals['_SIMULATESTEPRESPONSE']._serialized_start=467
  _globals['_SIMULATESTEPRESPONSE']._serialized_end=512
  _globals['_WORKFLOWSERVICE']._serialized_start=515
  _globals['_WORKFLOWSERVICE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
