# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surimi/v1/workflow.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'surimi/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from surimi.v1 import biomass_pb2 as surimi_dot_v1_dot_biomass__pb2
from surimi.v1 import species_price_pb2 as surimi_dot_v1_dot_species__price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18surimi/v1/workflow.proto\x12\tsurimi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17surimi/v1/biomass.proto\x1a\x1dsurimi/v1/species_price.proto\"\x81\x01\n\x0bInitRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x13\n\x0bscenario_id\x18\x02 \x01(\t\x12\x33\n\x0fstart_date_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tstep_size\x18\x04 \x01(\t\"\x0e\n\x0cInitResponse\"U\n\x13UpdatePricesRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\'\n\x06prices\x18\x02 \x03(\x0b\x32\x17.surimi.v1.SpeciesPrice\"\x16\n\x14UpdatePricesResponse\",\n\x13SimulateStepRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"\x16\n\x14SimulateStepResponse\"v\n\x14UpdateBiomassRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x18\n\x10measurement_unit\x18\x02 \x01(\t\x12-\n\rbiomass_grids\x18\x03 \x03(\x0b\x32\x16.surimi.v1.BiomassGrid\"\x17\n\x15UpdateBiomassResponse2\xc0\x02\n\x0fWorkflowService\x12\x37\n\x04Init\x12\x16.surimi.v1.InitRequest\x1a\x17.surimi.v1.InitResponse\x12O\n\x0cUpdatePrices\x12\x1e.surimi.v1.UpdatePricesRequest\x1a\x1f.surimi.v1.UpdatePricesResponse\x12O\n\x0cSimulateStep\x12\x1e.surimi.v1.SimulateStepRequest\x1a\x1f.surimi.v1.SimulateStepResponse\x12R\n\rUpdateBiomass\x12\x1f.surimi.v1.UpdateBiomassRequest\x1a .surimi.v1.UpdateBiomassResponseB!\n\x11\x65u.project.surimi\xaa\x02\x0bGrpc.Surimib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surimi.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eu.project.surimi\252\002\013Grpc.Surimi'
  _globals['_INITREQUEST']._serialized_start=129
  _globals['_INITREQUEST']._serialized_end=258
  _globals['_INITRESPONSE']._serialized_start=260
  _globals['_INITRESPONSE']._serialized_end=274
  _globals['_UPDATEPRICESREQUEST']._serialized_start=276
  _globals['_UPDATEPRICESREQUEST']._serialized_end=361
  _globals['_UPDATEPRICESRESPONSE']._serialized_start=363
  _globals['_UPDATEPRICESRESPONSE']._serialized_end=385
  _globals['_SIMULATESTEPREQUEST']._serialized_start=387
  _globals['_SIMULATESTEPREQUEST']._serialized_end=431
  _globals['_SIMULATESTEPRESPONSE']._serialized_start=433
  _globals['_SIMULATESTEPRESPONSE']._serialized_end=455
  _globals['_UPDATEBIOMASSREQUEST']._serialized_start=457
  _globals['_UPDATEBIOMASSREQUEST']._serialized_end=575
  _globals['_UPDATEBIOMASSRESPONSE']._serialized_start=577
  _globals['_UPDATEBIOMASSRESPONSE']._serialized_end=600
  _globals['_WORKFLOWSERVICE']._serialized_start=603
  _globals['_WORKFLOWSERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
