# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from surimi.v1 import workflow_pb2 as surimi_dot_v1_dot_workflow__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in surimi/v1/workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub(object):
    """The workflow service definition. All models should implement this interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialise = channel.unary_unary(
                '/surimi.v1.WorkflowService/Initialise',
                request_serializer=surimi_dot_v1_dot_workflow__pb2.InitialiseRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_workflow__pb2.InitialiseResponse.FromString,
                _registered_method=True)
        self.SimulateStep = channel.unary_unary(
                '/surimi.v1.WorkflowService/SimulateStep',
                request_serializer=surimi_dot_v1_dot_workflow__pb2.SimulateStepRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_workflow__pb2.SimulateStepResponse.FromString,
                _registered_method=True)
        self.Finalise = channel.unary_unary(
                '/surimi.v1.WorkflowService/Finalise',
                request_serializer=surimi_dot_v1_dot_workflow__pb2.FinaliseRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_workflow__pb2.FinaliseResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/surimi.v1.WorkflowService/Cancel',
                request_serializer=surimi_dot_v1_dot_workflow__pb2.CancelRequest.SerializeToString,
                response_deserializer=surimi_dot_v1_dot_workflow__pb2.CancelResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """The workflow service definition. All models should implement this interface
    """

    def Initialise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialise': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialise,
                    request_deserializer=surimi_dot_v1_dot_workflow__pb2.InitialiseRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_workflow__pb2.InitialiseResponse.SerializeToString,
            ),
            'SimulateStep': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateStep,
                    request_deserializer=surimi_dot_v1_dot_workflow__pb2.SimulateStepRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_workflow__pb2.SimulateStepResponse.SerializeToString,
            ),
            'Finalise': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalise,
                    request_deserializer=surimi_dot_v1_dot_workflow__pb2.FinaliseRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_workflow__pb2.FinaliseResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=surimi_dot_v1_dot_workflow__pb2.CancelRequest.FromString,
                    response_serializer=surimi_dot_v1_dot_workflow__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surimi.v1.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surimi.v1.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """The workflow service definition. All models should implement this interface
    """

    @staticmethod
    def Initialise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.WorkflowService/Initialise',
            surimi_dot_v1_dot_workflow__pb2.InitialiseRequest.SerializeToString,
            surimi_dot_v1_dot_workflow__pb2.InitialiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.WorkflowService/SimulateStep',
            surimi_dot_v1_dot_workflow__pb2.SimulateStepRequest.SerializeToString,
            surimi_dot_v1_dot_workflow__pb2.SimulateStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.WorkflowService/Finalise',
            surimi_dot_v1_dot_workflow__pb2.FinaliseRequest.SerializeToString,
            surimi_dot_v1_dot_workflow__pb2.FinaliseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surimi.v1.WorkflowService/Cancel',
            surimi_dot_v1_dot_workflow__pb2.CancelRequest.SerializeToString,
            surimi_dot_v1_dot_workflow__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
